### ISSUE TITLE
The "lets do nothing" option

### ISSUE THREAD

**Issue by martinheidegger** [martinheidegger/es6modules-nodejs#10]
There is the option of doing nothing. Maybe worth talking about.

**Comment by martinheidegger** [comment]
@williamkapke It would be nice to have a summary on the "lets do nothing" option

**Comment by ljharb** [comment]
While it's worth talking about, imo it would be a horrible idea to do nothing here, unless all browsers and node _all_ agree to do nothing.

There is a great danger here of forking the ecosystem. Unless literally everyone is conscientious about publishing backwards-compatible packages, packages _will_ be created that simply can't be consumed properly in a "do nothing" world - specifically, packages with only ES modules, from authors who don't care about being hostile to the majority of users that haven't upgraded to using them yet or have to support node/browser versions that don't have support yet. What `node` does, the entire JS tooling ecosystem will follow, and by doing _something_, the JS community will all unify on some One True Way of publishing backwards- and forwards- compatible packages, being able to freely use ES modules.

If `node` does nothing, we all run the risk of having multiple ways of doing this, and we'll be back in the world of "we need a UMD to abstract over the 6 module systems we have available because nobody can agree on which one we should all use".

**Comment by martinheidegger** [comment]
I pushed commit 45552012f3626106ede11ca1be3c3224a8b91bf0 with a mention of "do nothing" and I closed this issue because I think that there is nothing further to add. Please open another issue or PR with more information in case you disagree.
